namespace Test is
    @IF.not.v3()
    use Std = System.Console;
    @IF.not.v3()
    use object = System.Object;
    @IF.not.v3()
    use string = System.String;

    @IF.v3()
    use Std = IO.Std;

        use System.Exception;
    
    class Main is
        entry() static is
            @IL.entrypoint()

            try
                for i in 0..10 do
                    try
                        Std.out.write_line("outer: " + i);
    
                        for j in 0..10 do
                            Std.out.write_line("inner: " + j);

                            try
                                if i == j then
                                    Std.out.write_line("inner: " + i + " == " + j + " will throw Exception");
                                    throw new Exception("Exception: " + i + " == " + j);
                                fi
                                

                                if j == 2 then
                                    Std.out.write_line("inner: " + j + " == 2 will throw MyException");
                                    throw new MyException("MyException: " + j + " == 2");
                                fi
                                
                                if j >= 4 && j <= 5 then
                                    Std.out.write_line("inner: will continue");
                                    continue;
                                fi                                

                                if j >= 7 then
                                    Std.out.write_line("inner: will break on 7");
                                    break;
                                fi
                            catch ex: MyException
                                Std.out.write_line("inner: caught: " + ex.message);                                
                            yrt

                            Std.out.write_line("inner end");
                        od
    
                    catch ex: Exception
                        Std.out.write_line("outer: caught: " + ex.message);

                    yrt                
                od
                    

            catch ex: Exception
                Std.out.write_line("main: caught: " + ex.message);

            yrt
        si
    si

    class MyException: Exception is
        init(message: string) is super.init(message); si
    si   
si