try_catch_variable_finally_catch_variable() is
    try
        let x = 1;

    catch ex: System.Exception        
        
    finally
        let y = 2;

    catch ex: System.Exception        
        let z = 3;
    yrt
    
    return;
si
