namespace Test is
    @IF.not.v3()
    use Std = System.Console;
    @IF.not.v3()
    use object = System.Object;
    @IF.not.v3()
    use string = System.String;

    @IF.v3()
    use Std = IO.Std;

    use System;

    @IF.dotnet()
    class Main is
        entry() static is
            @IL.entrypoint()

            let test = new Test("Hello world");

            test.test();
        si
    si

    class Test is
        @IF.dotnet()
        message: string;

        @IF.legacy()
        count: int;

        @IF.dotnet()
        init(message: string) is
            self.message = message;
        si

        @IF.legacy()
        init(count: int) is
            self.count = count;           
        si
        
        test() is
            @IF.dotnet()
            Std.out.write_line(message);

            @IF.debug()
            Std.out.write_line("not expected: debug flag is not enabled");

            @IF.legacy()
            IO.Std.err.println("count is: " + count);
        si
    si

    @IF.legacy()
    class Broken is
        blah: DoesNotExist;

        test() is
            doSomethingDaft(bibble, bobble, blergh);
        si        
    si
    
si

namespace Ghul is
    @IF.not.v3()
    use Std = System.Console;
    @IF.not.v3()
    use object = System.Object;
    @IF.not.v3()
    use string = System.String;

    @IF.v3()
    use Std = IO.Std;

    @IF.legacy()
    class int is
        wibble: string;
    si    
si

@IF.legacy()
namespace System is
    @IF.not.v3()
    use Std = System.Console;
    @IF.not.v3()
    use object = System.Object;
    @IF.not.v3()
    use string = System.String;

    @IF.v3()
    use Std = IO.Std;

    class String is
        totally_broken: int;
    si

    class Exception is
        also_broken: int;
    si  
si

@IF.debug()
namespace System is
    @IF.not.v3()
    use Std = System.Console;
    @IF.not.v3()
    use object = System.Object;
    @IF.not.v3()
    use string = System.String;

    @IF.v3()
    use Std = IO.Std;

    class String is
        totally_broken: int;
    si

    class Exception is
        also_broken: int;
    si    
si
