namespace Test is
    use Std = IO.Std;

    use System.Exception;
    
    class Main is
        entry() static is            
            run("assert true should not throw", () -> void is
                assert true;
            si);

            run("assert 12345 != 67890 should not throw", () -> void is
                assert 12345 != 67890;
            si);

            run("assert false should throw with false as message", () -> void is
                assert false;
            si);

            run("assert 12345 == 67890 should throw with 12345 == 67890 as message", () -> void is
                assert 12345 == 67890;
            si);

            run("assert true else message should not throw", () -> void is
                assert true else "message";
            si);

            run("assert true else message should throw with message as message", () -> void is
                assert false else "message";
            si);

            run("assert true else string expression should not throw", () -> void is
                assert true else get_string() + " " + expression;
            si);

            run("assert true else string expression should throw with string expression as message", () -> void is
                assert false else get_string() + " " + expression;
            si);
        si

        get_string() -> string static => "string";
        expression: string static => "expression";

        run(description: string, test: () -> void) static is
            try
                Std.out.write_line(description);
                test();
                Std.out.write_line("did not throw");
            catch ex: Exception
                Std.out.write_line("threw: " + ex.get_type().name + " " + ex.message);
            finally
                Std.out.write_line();
            yrt
        si
    si
si