try_catch_variable_catch_finally() is
    try
        let x = 1;

    catch a: System.Exception

    catch 

    finally
        let y = 2;
    yrt
    
    return;
si
